// Mocks generated by Mockito 5.4.4 from annotations
// in truck_manager/test/app_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i12;

import 'package:googleapis/gmail/v1.dart' as _i2;
import 'package:googleapis/sheets/v4.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:truck_manager/services/capsules.dart' as _i3;
import 'package:truck_manager/services/firebase_service.dart' as _i4;
import 'package:truck_manager/services/line.dart' as _i13;
import 'package:truck_manager/services/mail.dart' as _i8;
import 'package:truck_manager/services/pdf_service.dart' as _i11;
import 'package:truck_manager/services/spread_sheet.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessage_0 extends _i1.SmartFake implements _i2.Message {
  _FakeMessage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeShiftCapsule_1 extends _i1.SmartFake implements _i3.ShiftCapsule {
  _FakeShiftCapsule_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInvoiceCapsule_2 extends _i1.SmartFake
    implements _i3.InvoiceCapsule {
  _FakeInvoiceCapsule_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i4.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> uploadFile({
    required String? storagePath,
    required _i6.File? file,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {
            #storagePath: storagePath,
            #file: file,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #uploadFile,
            [],
            {
              #storagePath: storagePath,
              #file: file,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> saveDocument({
    required String? collectionPath,
    required String? docId,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDocument,
          [],
          {
            #collectionPath: collectionPath,
            #docId: docId,
            #data: data,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #saveDocument,
            [],
            {
              #collectionPath: collectionPath,
              #docId: docId,
              #data: data,
            },
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [GmailService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGmailService extends _i1.Mock implements _i8.GmailService {
  MockGmailService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Message>> fetchMessageList(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMessageList,
          [query],
        ),
        returnValue: _i5.Future<List<_i2.Message>>.value(<_i2.Message>[]),
      ) as _i5.Future<List<_i2.Message>>);

  @override
  _i5.Future<_i2.Message> getMessageDetails(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getMessageDetails,
          [id],
        ),
        returnValue: _i5.Future<_i2.Message>.value(_FakeMessage_0(
          this,
          Invocation.method(
            #getMessageDetails,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Message>);

  @override
  _i5.Future<List<int>> fetchAttachment(
    String? messageId,
    String? attachmentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAttachment,
          [
            messageId,
            attachmentId,
          ],
        ),
        returnValue: _i5.Future<List<int>>.value(<int>[]),
      ) as _i5.Future<List<int>>);

  @override
  _i5.Future<void> markAsRead(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GoogleSheetsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSheetsService extends _i1.Mock
    implements _i9.GoogleSheetsService {
  MockGoogleSheetsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set sheetsApi(_i10.SheetsApi? _sheetsApi) => super.noSuchMethod(
        Invocation.setter(
          #sheetsApi,
          _sheetsApi,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get spreadsheetId => (super.noSuchMethod(
        Invocation.getter(#spreadsheetId),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#spreadsheetId),
        ),
      ) as String);

  @override
  set spreadsheetId(String? _spreadsheetId) => super.noSuchMethod(
        Invocation.setter(
          #spreadsheetId,
          _spreadsheetId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.ShiftCapsule> retriveTruckData(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #retriveTruckData,
          [date],
        ),
        returnValue: _i5.Future<_i3.ShiftCapsule>.value(_FakeShiftCapsule_1(
          this,
          Invocation.method(
            #retriveTruckData,
            [date],
          ),
        )),
      ) as _i5.Future<_i3.ShiftCapsule>);
}

/// A class which mocks [PdfService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfService extends _i1.Mock implements _i11.PdfService {
  MockPdfService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Uint8List get japaneseFont => (super.noSuchMethod(
        Invocation.getter(#japaneseFont),
        returnValue: _i12.Uint8List(0),
      ) as _i12.Uint8List);

  @override
  _i5.Future<_i3.InvoiceCapsule> processToJpgWithWatermark(
    _i6.File? sourcePdf,
    _i3.ShiftCapsule? shift,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processToJpgWithWatermark,
          [
            sourcePdf,
            shift,
          ],
        ),
        returnValue: _i5.Future<_i3.InvoiceCapsule>.value(_FakeInvoiceCapsule_2(
          this,
          Invocation.method(
            #processToJpgWithWatermark,
            [
              sourcePdf,
              shift,
            ],
          ),
        )),
      ) as _i5.Future<_i3.InvoiceCapsule>);

  @override
  _i5.Future<String> extractTextFromPdf(_i6.File? pdfFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTextFromPdf,
          [pdfFile],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #extractTextFromPdf,
            [pdfFile],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [LineNotifyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLineNotifyService extends _i1.Mock implements _i13.LineNotifyService {
  MockLineNotifyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get channelAccessToken => (super.noSuchMethod(
        Invocation.getter(#channelAccessToken),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#channelAccessToken),
        ),
      ) as String);

  @override
  String get targetUserId => (super.noSuchMethod(
        Invocation.getter(#targetUserId),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#targetUserId),
        ),
      ) as String);

  @override
  _i5.Future<String> sendOrderNotifications(
    List<_i3.OrderCapsule>? orders, {
    bool? isDebug = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOrderNotifications,
          [orders],
          {#isDebug: isDebug},
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #sendOrderNotifications,
            [orders],
            {#isDebug: isDebug},
          ),
        )),
      ) as _i5.Future<String>);
}
