name: Send LINE Notification

on:
  push:
    branches:
      - main # mainブランチへのプッシュをトリガーにします

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8' # ご利用のFlutterのバージョンに合わせてください
          channel: 'stable'

      - name: Run integration test and generate JSON
        run: |
          cd truck_manager
          mkdir -p $TMP_DIR $FONT_DIR $CONFIG_DIR
          dart pub get
          dart run lib/app.dart
        env:
          # ディレクトリ設定 (GitHub Actionsの標準パスを使用)
          TMP_DIR: ${{ github.workspace }}/tmp
          FONT_DIR: ${{ github.workspace }}/fonts
          CONFIG_DIR: ${{ github.workspace }}/config

          # API 認証情報 (先ほどリネームした命名規則を適用)
          OAUTH_ID: ${{ secrets.OAUTH_ID }}
          OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
          G_REFRESH_TOKEN: ${{ secrets.G_REFRESH_TOKEN }}
          GOOGLE_SERVICE_CRED: ${{secrets.GOOGLE_SERVICE_CRED}}

          # 外部サービス連携
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
          LINE_TARGET_USER_ID: ${{ secrets.LINE_TARGET_USER_ID }}

          # スプレッドシート設定
          SHIFT_SHEET_ID: ${{ secrets.SHIFT_SHEET_ID }}

          # ワークフロー制御用
          TARGET: "${{ secrets.TARGET }}"

          #エラー時対応用
          GAS_WEB_HOOK: ${{ secrets.GAS_WEB_HOOK }}
